# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'elevRechDesign.ui',
# licensing of 'elevRechDesign.ui' applies.
#
# Created: Sat Jul 27 16:36:53 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1093, 853)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labAcad = QtWidgets.QLabel(self.centralwidget)
        self.labAcad.setObjectName("labAcad")
        self.verticalLayout.addWidget(self.labAcad)
        self.cbAcad = QtWidgets.QComboBox(self.centralwidget)
        self.cbAcad.setObjectName("cbAcad")
        self.verticalLayout.addWidget(self.cbAcad)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labEtab = QtWidgets.QLabel(self.centralwidget)
        self.labEtab.setObjectName("labEtab")
        self.verticalLayout_2.addWidget(self.labEtab)
        self.cbEtab = QtWidgets.QComboBox(self.centralwidget)
        self.cbEtab.setObjectName("cbEtab")
        self.verticalLayout_2.addWidget(self.cbEtab)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labClas = QtWidgets.QLabel(self.centralwidget)
        self.labClas.setObjectName("labClas")
        self.verticalLayout_3.addWidget(self.labClas)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labMatier = QtWidgets.QLabel(self.centralwidget)
        self.labMatier.setObjectName("labMatier")
        self.verticalLayout_5.addWidget(self.labMatier)
        self.cbMatier = QtWidgets.QComboBox(self.centralwidget)
        self.cbMatier.setObjectName("cbMatier")
        self.verticalLayout_5.addWidget(self.cbMatier)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labElev = QtWidgets.QLabel(self.centralwidget)
        self.labElev.setObjectName("labElev")
        self.verticalLayout_4.addWidget(self.labElev)
        self.leElev = QtWidgets.QLineEdit(self.centralwidget)
        self.leElev.setObjectName("leElev")
        self.verticalLayout_4.addWidget(self.leElev)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labRech = QtWidgets.QLabel(self.centralwidget)
        self.labRech.setObjectName("labRech")
        self.verticalLayout_6.addWidget(self.labRech)
        self.pbOK = QtWidgets.QPushButton(self.centralwidget)
        self.pbOK.setObjectName("pbOK")
        self.verticalLayout_6.addWidget(self.pbOK)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.lablistResult = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.lablistResult.setFont(font)
        self.lablistResult.setObjectName("lablistResult")
        self.verticalLayout_7.addWidget(self.lablistResult)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_7.addWidget(self.tableWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1093, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.labAcad.setText(QtWidgets.QApplication.translate("MainWindow", "Academies", None, -1))
        self.labEtab.setText(QtWidgets.QApplication.translate("MainWindow", "Etablissements", None, -1))
        self.labClas.setText(QtWidgets.QApplication.translate("MainWindow", "Classes", None, -1))
        self.labMatier.setText(QtWidgets.QApplication.translate("MainWindow", "Matieres", None, -1))
        self.labElev.setText(QtWidgets.QApplication.translate("MainWindow", "Eleves", None, -1))
        self.labRech.setText(QtWidgets.QApplication.translate("MainWindow", "Recherche", None, -1))
        self.pbOK.setText(QtWidgets.QApplication.translate("MainWindow", "Ok", None, -1))
        self.lablistResult.setText(QtWidgets.QApplication.translate("MainWindow", "liste de resultats", None, -1))

