# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/ficheelevey25772.ui',
# licensing of '/tmp/ficheelevey25772.ui' applies.
#
# Created: Sun Aug 11 14:46:07 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1036, 887)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.photo = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.photo.sizePolicy().hasHeightForWidth())
        self.photo.setSizePolicy(sizePolicy)
        self.photo.setMaximumSize(QtCore.QSize(200, 200))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("../../Pictures/vision board/chatigre.png"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.horizontalLayout_3.addWidget(self.photo)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.NOM = QtWidgets.QLabel(Dialog)
        self.NOM.setObjectName("NOM")
        self.gridLayout.addWidget(self.NOM, 0, 0, 1, 1)
        self.NOMnom = QtWidgets.QLabel(Dialog)
        self.NOMnom.setObjectName("NOMnom")
        self.gridLayout.addWidget(self.NOMnom, 0, 2, 1, 1)
        self.ADRESSE = QtWidgets.QLabel(Dialog)
        self.ADRESSE.setObjectName("ADRESSE")
        self.gridLayout.addWidget(self.ADRESSE, 2, 0, 1, 1)
        self.ADRESSEadresse = QtWidgets.QLabel(Dialog)
        self.ADRESSEadresse.setObjectName("ADRESSEadresse")
        self.gridLayout.addWidget(self.ADRESSEadresse, 2, 2, 1, 1)
        self.PRENOMprenom = QtWidgets.QLabel(Dialog)
        self.PRENOMprenom.setObjectName("PRENOMprenom")
        self.gridLayout.addWidget(self.PRENOMprenom, 1, 2, 1, 1)
        self.PRENOM = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.PRENOM.setFont(font)
        self.PRENOM.setMargin(0)
        self.PRENOM.setObjectName("PRENOM")
        self.gridLayout.addWidget(self.PRENOM, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setShowGrid(True)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.radarchart = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radarchart.sizePolicy().hasHeightForWidth())
        self.radarchart.setSizePolicy(sizePolicy)
        self.radarchart.setObjectName("radarchart")
        self.horizontalLayout.addWidget(self.radarchart)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None, -1))
        self.NOM.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">NOM</span></p></body></html>", None, -1))
        self.NOMnom.setText(QtWidgets.QApplication.translate("Dialog", "TextLabel", None, -1))
        self.ADRESSE.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">ADRESSE</span></p></body></html>", None, -1))
        self.ADRESSEadresse.setText(QtWidgets.QApplication.translate("Dialog", "TextLabel", None, -1))
        self.PRENOMprenom.setText(QtWidgets.QApplication.translate("Dialog", "TextLabel", None, -1))
        self.PRENOM.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt;\">PRENOM</span></p></body></html>", None, -1))
        self.radarchart.setText(QtWidgets.QApplication.translate("Dialog", "radar chart", None, -1))

